name: Lua README updater

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-lua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Lua
        run: sudo apt update && sudo apt install -y lua5.4

      - name: Run Lua script
        run: lua scripts/readme_gen.lua

      - name: Commit changes
        run: |
          git diff
          git config user.name "github-actions"
          git config user.email "github-actions@no-reply.com"
          git add README.md

          git diff --cached --quiet && exit 0

          git commit -m "docs: update README plugins" -m "This commit was generated automatically. Update the plugins list of the Neovim section of the README.md file"
          git push

